global_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.1
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
